services:
  api:
    build: .
    container_name: lark-api
    ports:
      - "9101:9100"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - lark-network

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
     - "6380:6379"
    networks:
      - lark-network

networks:
  lark-network:
    driver: bridge
